name: Publish to Packagist

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build for Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build for macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          rustup target add x86_64-apple-darwin
          cargo build --release --target x86_64-apple-darwin

      - name: Build for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          rustup target add x86_64-pc-windows-gnu
          cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            target/x86_64-unknown-linux-gnu/release/liboxide_parser_wasm.so
            target/x86_64-apple-darwin/release/liboxide_parser_wasm.dylib
            target/x86_64-pc-windows-gnu/release/oxide_parser_wasm.dll

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: collected-artifacts

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: wind-press/oxide-parser-php
          ref: main
          path: remote-repository
          token: ${{ secrets.ORG_DEV_PAT }}

      - name: Copy artifacts to target repository
        run: |
          mkdir -p remote-repository/php/ext/
          cp -a collected-artifacts/* remote-repository/php/ext/

      - name: Setup Git
        run: |
          git config --global user.name "Joshua Gugun Siagian"
          git config --global user.email "suabahasa@gmail.com"

      - name: Commit and tag
        working-directory: remote-repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add --all
          git commit -m "oxide-parser-wasm ${GITHUB_REF#refs/tags/}"
          git push
          git tag ${GITHUB_REF#refs/tags/} -m "${GITHUB_REF#refs/tags/}"
          git push origin ${GITHUB_REF#refs/tags/}
