# builds the content of http://github.com/wind-press/windpress
# inspiration from https://github.com/rectorphp/rector-src/blob/main/.github/workflows/build_scoped_rector.yaml
# TODO: trigger the FREE build only when the PRO build is successful. reference: https://github.blog/changelog/2022-09-08-github-actions-use-github_token-with-workflow_dispatch-and-repository_dispatch/
name: Publish to packagist

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
        # sometime, when 2 or more consecutive PRs merged, the checkout wind-press/windpress is overlapped
        # and reverting other commit change
        # this should not happen on create a tag, so wait first
        - name: "Wait before checkout on create a tag"
          if: "startsWith(github.ref, 'refs/tags/')"
          run: sleep 20

        - uses: actions/checkout@v4

        # Set up Rust toolchain
        - name: Set up Rust
          uses: dtolnay/rust-toolchain@stable
          with:
            targets: |
              x86_64-unknown-linux-gnu
              x86_64-apple-darwin
              x86_64-pc-windows-gnu

        # Install dependencies for cross-compilation
        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y musl-tools mingw-w64

        # Build for Linux (.so)
        - name: Build for Linux
          run: |
            cargo build --release --target x86_64-unknown-linux-gnu

        # Build for macOS (.dylib)
        - name: Build for macOS
          run: |
            cargo build --release --target x86_64-apple-darwin

        # Build for Windows (.dll)
        - name: Build for Windows
          run: |
            cargo build --release --target x86_64-pc-windows-gnu

        # Prepare output directory
        - name: Prepare output
          run: |
            mkdir -p php/ext/
            cp target/x86_64-unknown-linux-gnu/release/liboxide_parser_wasm.so php/ext/
            cp target/x86_64-apple-darwin/release/liboxide_parser_wasm.dylib php/ext/
            cp target/x86_64-pc-windows-gnu/release/oxide_parser_wasm.dll php/ext/

        # clone remote repository, so we can push it
        - uses: actions/checkout@v4
          with:
            repository: wind-press/oxide-parser-php
            ref: main
            path: remote-repository
            token: ${{ secrets.ORG_DEV_PAT }}

        # remove remote files, to avoid piling up dead code in remote repository
        - working-directory: remote-repository
          run: |
            git rm -rf .
            git clean -fxd

        # copy files to remote repository
        - run: cp -a php/. remote-repository

        # setup git
        - working-directory: remote-repository
          run: |
            git config user.name "Joshua Gugun Siagian"
            git config user.email suabahasa@gmail.com

        # commit metadata
        - name: "Get Git log"
          id: git-log
          run: |
              echo "log<<EOF" >> $GITHUB_OUTPUT
              echo "$(git log ${{ github.event.before }}..${{ github.event.after }} --reverse --pretty='https://github.com/wind-press/oxide-parser-wasm/commit/%H %s')" >> $GITHUB_OUTPUT
              echo 'EOF' >> $GITHUB_OUTPUT

        # publish it to remote repository with tag
        - name: "Commit Prefixed - tag"
          working-directory: remote-repository
          if: "startsWith(github.ref, 'refs/tags/')"
          env:
              INPUT_LOG: ${{ steps.git-log.outputs.log }}
          run: |
            git add --all
            git commit -m "oxide-parser-wasm ${GITHUB_REF#refs/tags/}" -m "$INPUT_LOG"
            git push --quiet origin main
            git tag ${GITHUB_REF#refs/tags/} -m "${GITHUB_REF#refs/tags/}"
            git push --quiet origin ${GITHUB_REF#refs/tags/}

